# -*- coding: utf-8 -*-
"""python project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UxG6tXhLeRi67EC-gqcznKq0oLGZIbAp
"""

!sudo apt-get install -y fonts-noto-cjk
!rm -rf ~/.cache/matplotlib

print("Đã cài đặt font và xóa bộ đệm font. Vui lòng KHỞI ĐỘNG LẠI THỜI GIAN CHẠY (Runtime -> Restart runtime) ngay bây giờ, sau đó chạy ô tiếp theo để áp dụng cài đặt font.")

import matplotlib.pyplot as plt
import seaborn as sns

# Đặt kiểu hiển thị gọn gàng và hiện đại cho tất cả biểu đồ
plt.style.use('seaborn-v0_8-darkgrid')

# Cấu hình Matplotlib sử dụng font hỗ trợ ký tự tiếng Việt
plt.rcParams['font.family'] = 'sans-serif' # Sử dụng họ font sans-serif chung
plt.rcParams['font.sans-serif'] = ['Noto Sans CJK JP', 'DejaVu Sans', 'Arial', 'Liberation Sans'] # Ưu tiên Noto Sans CJK JP

from google.colab import drive
drive.mount('/content/ggdrive')

import pandas as pd
data = pd.read_csv(
    '/content/ggdrive/MyDrive/python project/sleep_health_lifestyle_dataset.csv'
    )
data

"""**Giới thiệu đề tài:**

Mục tiêu của project là kiểm định xem thời lượng ngủ trung bình giữa nam và nữ có khác nhau hay không. Đồng thời phân tích mối quan hệ giữa mức độ căng thẳng và thời lượng ngủ bằng các phương pháp thống kê.
"""

data.info()

data.describe()

data.isnull().sum()

"""Kết quả cho thấy không có giá trị thiếu nên không cần xử lý."""

data=data.dropna()

data.columns

data.duplicated().sum()

"""Dataset không có bản ghi trùng lặp."""

sleep = data["Sleep Duration (hours)"]

print("Giá trị trung bình:", sleep.mean())
print("Giá trị trung vị:", sleep.median())
print("Giá trị Mode:", sleep.mode()[0])
print("Độ lệch chuẩn:", sleep.std())
print("Phương sai:", sleep.var())
print("Giá trị nhỏ nhất:", sleep.min())
print("Giá trị lớn nhất:", sleep.max())

# Nhận xét: Thời lượng ngủ trung bình của mẫu là 8.11 giờ.

"""Thời lượng ngủ trung bình của mẫu là 8.1 giờ. Độ lệch chuẩn cho thấy mức độ phân tán của dữ liệu quanh giá trị trung bình"""

from scipy import stats

mean = sleep.mean()
sem = stats.sem(sleep)

ci = stats.t.interval(
    confidence=0.95,
    df=len(sleep)-1,
    loc=mean,
    scale=sem
)

print("Khoảng tin cậy 95%:", ci)

"""Với mức tin cậy 95%, thời lượng ngủ trung bình của tổng thể nằm trong khoảng từ 7.6 đến 8.6 giờ.

# Independent T-Test

## Mục tiêu
Kiểm tra xem thời lượng ngủ trung bình giữa nam và nữ có khác nhau hay không.

### Giả thuyết

- H₀: Thời lượng ngủ trung bình của nam và nữ là như nhau.
- H₁: Thời lượng ngủ trung bình của nam và nữ là khác nhau.

Mức ý nghĩa α = 0.05.
"""

from scipy.stats import ttest_ind

male = data[data["Gender"] == "Male"]["Sleep Duration (hours)"]
female = data[data["Gender"] == "Female"]["Sleep Duration (hours)"]

t_stat, p_value = ttest_ind(male, female)

print("Giá trị T-statistic:", t_stat)
print("Giá trị P-value:", p_value)

alpha = 0.05
print("Giá trị T-statistic:", t_stat)
print("Giá trị P-value:", p_value)
if p_value < alpha:
    print("Bác bỏ H0")
    print("=> Thời lượng ngủ trung bình giữa nam và nữ có sự khác biệt.")
else:
    print("Không bác bỏ H0")
    print("=> Chưa có đủ bằng chứng để kết luận thời lượng ngủ trung bình giữa nam và nữ khác nhau.")

"""#### Nhận xét về Independent T-Test (So sánh thời lượng ngủ giữa nam và nữ)

Kết quả kiểm định Independent T-Test cho thấy giá trị T-statistic là **0.453** và giá trị P-value là **0.651**.

Với mức ý nghĩa (alpha) là 0.05, P-value (0.651) lớn hơn nhiều so với alpha. Do đó, chúng ta **không bác bỏ giả thuyết null (H₀)**.

Điều này có nghĩa là chưa có đủ bằng chứng thống kê để kết luận rằng có sự khác biệt có ý nghĩa về thời lượng ngủ trung bình giữa nam và nữ trong bộ dữ liệu này.

# Pearson Correlation

## Giả thuyết

- H₀: Không có mối tương quan giữa mức độ căng thẳng và thời lượng ngủ.
- H₁: Có mối tương quan giữa mức độ căng thẳng và thời lượng ngủ.
"""

from scipy.stats import pearsonr

r, p = pearsonr(
    data["Stress Level (scale: 1-10)"],
    data["Sleep Duration (hours)"]
)

print("Hệ số tương quan:", r)
print("Giá trị P-value:", p)

alpha = 0.05
print("Correlation coefficient:", r)
print("P-value:", p)
if p < alpha:
    print("Bác bỏ H0")
    print("Có mối tương quan giữa Stress Level và Sleep Duration.")
else:
    print("Không bác bỏ H0")
    print("Chưa có đủ bằng chứng về mối tương quan.")

"""#### Nhận xét về tương quan Pearson giữa mức độ căng thẳng và thời lượng ngủ

Kết quả kiểm định tương quan Pearson cho thấy hệ số tương quan (r) là **-0.044**, một giá trị rất gần 0, chỉ ra mối quan hệ tuyến tính rất yếu hoặc không đáng kể giữa mức độ căng thẳng và thời lượng ngủ.

Giá trị P-value thu được là **0.645**, lớn hơn nhiều so với mức ý nghĩa thông thường (alpha = 0.05). Do đó, chúng ta không bác bỏ giả thuyết null (H₀). Điều này có nghĩa là chưa có đủ bằng chứng thống kê để kết luận rằng có mối tương quan tuyến tính đáng kể giữa mức độ căng thẳng và thời lượng ngủ trong bộ dữ liệu này.
"""

plt.figure(figsize=(10, 6))
sns.histplot(data["Sleep Duration (hours)"], bins=15, kde=True, color='skyblue')
plt.title("Distribution of Sleep Duration", fontsize=16)
plt.xlabel("Thời lượng ngủ (giờ)", fontsize=12)
plt.ylabel("Tần suất", fontsize=12)
plt.xticks(fontsize=10)
plt.yticks(fontsize=10)
plt.tight_layout()
plt.show()

"""#### Nhận xét về Biểu đồ phân phối thời lượng ngủ (Distribution of Sleep Duration)

Biểu đồ cho thấy một phân phối hai đỉnh rõ rệt. Một đỉnh nằm trong khoảng 4.0 đến 5.0 giờ và một đỉnh khác, nổi bật hơn, nằm trong khoảng 9.5 đến 11.0 giờ. Điều này chỉ ra rằng có ít nhất hai nhóm khác biệt trong tập dữ liệu với các thói quen ngủ khác nhau (ví dụ: người ngủ ít và người ngủ nhiều). Phân phối này không theo phân phối chuẩn.
"""

plt.figure(figsize=(6, 4))
sns.boxplot(y=data["Sleep Duration (hours)"], color='lightgreen')
plt.title("Boxplot of Sleep Duration", fontsize=16)
plt.ylabel("Thời lượng ngủ (giờ)", fontsize=12)
plt.yticks(fontsize=10)
plt.tight_layout()
plt.show()

"""#### Nhận xét về Biểu đồ hộp của thời lượng ngủ (Boxplot of Sleep Duration)

Biểu đồ hộp của thời lượng ngủ minh họa sự phân tán của dữ liệu. Đường trung vị nằm quanh 8.85 giờ. Hộp, đại diện cho khoảng tứ phân vị (IQR), khá rộng, cho thấy sự biến động đáng kể về thời lượng ngủ. Không có giá trị ngoại lệ rõ ràng trong biểu đồ này. Các râu kéo dài đến giá trị nhỏ nhất (4.1 giờ) và lớn nhất (12.0 giờ), thể hiện toàn bộ phạm vi thời lượng ngủ mà không có giá trị cực đoan nào được phát hiện bởi tiêu chí ngoại lệ của biểu đồ hộp. Đường trung vị không nằm chính giữa hộp và các râu không đối xứng, phù hợp với phân phối hai đỉnh đã thấy trong biểu đồ tần suất.
"""

plt.figure(figsize=(10, 7))
sns.scatterplot(
    x=data["Stress Level (scale: 1-10)"],
    y=data["Sleep Duration (hours)"],
    color='coral',
    alpha=0.7
)
plt.xlabel("Mức độ căng thẳng (Thang điểm: 1-10)", fontsize=12)
plt.ylabel("Thời lượng ngủ (giờ)", fontsize=12)
plt.title("Stress vs Sleep Duration", fontsize=16)
plt.xticks(fontsize=10)
plt.yticks(fontsize=10)
plt.tight_layout()
plt.show()

"""#### Nhận xét về Biểu đồ phân tán giữa mức độ căng thẳng và thời lượng ngủ (Stress vs Sleep Duration)

Biểu đồ phân tán giữa 'Mức độ căng thẳng (thang điểm 1-10)' và 'Thời lượng ngủ (giờ)' không cho thấy mối quan hệ tuyến tính rõ ràng hay xu hướng cụ thể nào. Các điểm dữ liệu dường như được phân tán ngẫu nhiên, cho thấy khi mức độ căng thẳng thay đổi, không có mô hình tăng hoặc giảm thời lượng ngủ một cách nhất quán. Quan sát trực quan này được củng cố mạnh mẽ bởi phân tích tương quan Pearson, với hệ số tương quan (r) xấp xỉ -0.044 và giá trị p (p) là 0.644. Vì giá trị p lớn hơn nhiều so với mức ý nghĩa thông thường (ví dụ: 0.05), chúng ta không bác bỏ giả thuyết không, kết luận rằng không có mối tương quan tuyến tính đáng kể về mặt thống kê giữa mức độ căng thẳng và thời lượng ngủ trong tập dữ liệu này.

**KẾT LUẬN**

Trong project này, bộ dữ liệu Sleep Health and Lifestyle đã được sử dụng để thực hiện phân tích kiểm định thống kê về thời lượng ngủ và các yếu tố liên quan. Trước khi phân tích, dữ liệu đã được kiểm tra về giá trị thiếu, dữ liệu trùng lặp và các đặc điểm thống kê cơ bản nhằm đảm bảo độ tin cậy của kết quả.

Kết quả thống kê mô tả và các biểu đồ trực quan cho thấy thời lượng ngủ của các đối tượng dao động trong khoảng từ khoảng 4 đến 12 giờ, dữ liệu tương đối ổn định và không xuất hiện các giá trị ngoại lệ đáng kể.

Đối với kiểm định Independent t-test, kết quả thu được là T-statistic = 0.453 và P-value = 0.651. Do giá trị P-value lớn hơn mức ý nghĩa 0.05, nên không bác bỏ giả thuyết H₀. Điều này cho thấy chưa có đủ bằng chứng thống kê để kết luận thời lượng ngủ trung bình giữa nam và nữ có sự khác biệt trong bộ dữ liệu được nghiên cứu.

Đối với kiểm định tương quan Pearson, kết quả cho thấy chưa có đủ bằng chứng thống kê để khẳng định tồn tại mối tương quan giữa mức độ căng thẳng (Stress Level) và thời lượng ngủ (Sleep Duration). Nói cách khác, trong phạm vi của bộ dữ liệu này, chưa thể kết luận rằng mức độ căng thẳng có ảnh hưởng đáng kể đến thời lượng ngủ.

Nhìn chung, project đã thực hiện đầy đủ các bước của một bài phân tích kiểm định thống kê, bao gồm: đọc và làm sạch dữ liệu, thống kê mô tả, trực quan hóa dữ liệu, xây dựng giả thuyết, thực hiện các phép kiểm định thống kê và diễn giải kết quả dựa trên p-value. Qua project này có thể thấy Python là một công cụ hiệu quả trong việc hỗ trợ phân tích dữ liệu và đưa ra các kết luận dựa trên cơ sở thống kê.
"""